language: java

jdk:
  - oraclejdk8

branches:
  only:
    - travis

cache:
  directories:
    - $HOME/.m2

before_install:
  - export TZ="America/Los_Angeles"
  - echo "MAVEN_OPTS='-DcheckedArithmetic=true'" > ~/.mavenrc
  - date

notifications:
  hipchat: HIPCHAT_TOKEN@Gosu
