language: java

jdk:
  - oraclejdk8

branches:
  only:
    - travis

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo "MAVEN_OPTS='-DcheckedArithmetic=true -Xmx1g'" > ~/.mavenrc
  - export TZ="America/Los_Angeles"
  - date
  - mvn -f gosu-test/pom.xml help:active-profiles -B -V

# completely skip test compilation and execution for the install step
# speeds up the build significantly since incremental compilation does not work
install: mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V

notifications:
  hipchat:
    secure: "MuBdpvekaX+4oorVi1B3tqJlb3znq7XCUDHOIh8gcmEOoXzxSMcuasL+VNisYILToxX7R0s9qA/k/lS7nMXuuzlf8FpWqkywxC2DUnwR8zzSdCj5edaH3Zb8x5tck84eAEF8bNoR7UusPmMXT1y1390za9FCdMMdkEosWf1nQm4="
